config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'recipes#index'
  get '/search', to: 'recipes#search', as: 'search_recipes'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	belongs_to :recipe

  validates :name, presence: true, length: { maximum: 100 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

	has_many :ingredients

  validates :name, presence: true, length: { maximum: 100 }
  validates :instructions, presence: true, length: { maximum: 1000 }
  validates :cooking_time, presence: true, numericality: { greater_than: 0 }

  mapping do
    indexes :name, type: 'text'
    indexes :instructions, type: 'text'
    indexes :cooking_time, type: 'integer'
    indexes :ingredients do
      indexes :name, type: 'text'
    end
  end

  def as_indexed_json(_options = {})
    self.as_json(include: { ingredients: { only: :name } })
  end

  def self.search(cuisine, ingredient)
    query = {}
    query[:match] = { name: cuisine } if cuisine.present?
    query[:match] = { 'ingredients.name': ingredient } if ingredient.present?

    __elasticsearch__.search(query)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def index
    @recipes = Recipe.all
  end

  def search
    @recipes = Recipe.search(params[:cuisine], params[:ingredient])
    if @recipes.empty?
      flash.now[:notice] = 'No recipes found.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/search.html.erb
<h1>Search Recipes</h1>

<%= form_tag(search_recipes_path, method: :get) do %>
  <div>
    <%= label_tag 'Cuisine' %>
    <%= text_field_tag 'cuisine' %>
  </div>

  <div>
    <%= label_tag 'Ingredient' %>
    <%= text_field_tag 'ingredient' %>
  </div>

  <%= submit_tag 'Search' %>
<% end %>

<% if @recipes.any? %>
  <h2>Matching Recipes</h2>

  <ul>
    <% @recipes.each do |recipe| %>
      <li>
        <strong><%= recipe.name %></strong> - Cooking time: <%= recipe.cooking_time %> min
        <br>
        <%= recipe.instructions %>
        <br>
        Ingredients: <%= recipe.ingredients.pluck(:name).join(', ') %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No recipes found.</p>
<% end %>